pre-commit:
  parallel: true
  commands:
    format:
      run: pnpm format --log-level warn && git add -u
    lint:
      run: pnpm lint:fix
    typecheck:
      run: pnpm ts:check --noEmit

commit-msg:
  commands:
    lint-commit:
      run: pnpm commitlint --edit "$1"
