services:
  ludora-showcase-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4050:4050"
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm run dev
