services:
  ludora-showcase-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4050:4050'
    volumes:
      - .:/src
    environment:
      - NODE_ENV=development
    command: sh -c "pnpm install && pnpm run dev"
